package interfaz;

public class Seccion_comentarios_Usuario_no_registrado_item extends Seccion_comentarios_item {
	public Seccion_comentarios_Usuario_no_registrado _seccion_comentarios_Usuario_no_registrado;
}